# Change these first
owner: SebastienFCT # Your GitHub username
repo: server-statuses # Your GitHub repository name

# Add your sites here
sites:
  - name: Easy PDF Signer - Promotional Website
    url: https://easypdfsigner.ca
  - name: Easy PDF Signer - Web Application
    url: https://account.easypdfsigner.ca/login

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /server-statuses
  # logoUrl: https://scontent.fyyc2-1.fna.fbcdn.net/v/t1.0-9/117934337_113988470420922_9073664865379495787_o.jpg?_nc_cat=109&ccb=3&_nc_sid=09cbfe&_nc_ohc=NBHXKEl_mYcAX-3ENWE&_nc_ht=scontent.fyyc2-1.fna&oh=600bd75254156240bf136e8d54a9297d&oe=604CB1EB
  name: A.A.S. Development Studios Ltd.
  introTitle: "**A.A.S.** server statuses."
  introMessage: This is the statuses for our servers
  # navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/15 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
